export const categories = [
    { id: '1', name: 'All', icon: 'grid-outline' },
    { id: '2', name: 'Woman', icon: 'woman-outline' },
    { id: '3', name: 'Man', icon: 'man-outline' },
    { id: '4', name: 'Kids', icon: 'happy-outline' },
    { id: '5', name: 'Shoes', icon: 'footsteps-outline' },
    { id: '6', name: 'Bags', icon: 'bag-outline' },
];

export const products = [
    {
        id: '1',
        name: 'Essential Bag',
        price: 5750000,
        oldPrice: null,
        image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=500&fit=crop',
        category: 'Bags',
        colors: ['#000000', '#8B4513', '#D2B48C'],
        sizes: ['S', 'M', 'L'],
        rating: 4.8,
        reviews: 128,
        description: 'Premium leather essential bag with adjustable strap. Perfect for everyday use with multiple compartments for organization.',
    },
    {
        id: '2',
        name: 'Jeka Jacket',
        price: 185000,
        oldPrice: null,
        image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=500&fit=crop',
        category: 'Man',
        colors: ['#000000', '#1a1a2e', '#4a4e69'],
        sizes: ['S', 'M', 'L', 'XL'],
        rating: 4.5,
        reviews: 89,
        description: 'Comfortable and stylish jacket made from premium materials. Water-resistant exterior with warm interior lining.',
    },
    {
        id: '3',
        name: 'Accent Leisure Chair',
        price: 950000,
        oldPrice: null,
        image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=400&h=500&fit=crop',
        category: 'All',
        colors: ['#D2B48C', '#8B4513', '#000000'],
        sizes: [],
        rating: 4.9,
        reviews: 56,
        description: 'Modern accent leisure chair with ergonomic design. Upholstered in premium fabric with solid wood legs.',
    },
    {
        id: '4',
        name: 'Wing Chair',
        price: 950000,
        oldPrice: null,
        image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=500&fit=crop',
        category: 'All',
        colors: ['#556B2F', '#8B4513', '#D2B48C'],
        sizes: [],
        rating: 4.7,
        reviews: 42,
        description: 'Classic wing chair design with modern comfort. Deep cushioning with high-quality upholstery.',
    },
    {
        id: '5',
        name: 'Sports Tech Sneakers',
        price: 6500000,
        oldPrice: null,
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=500&fit=crop',
        category: 'Shoes',
        colors: ['#FF0000', '#000000', '#FFFFFF'],
        sizes: ['38', '39', '40', '41', '42', '43'],
        rating: 4.6,
        reviews: 234,
        description: 'High-performance sports tech sneakers with advanced cushioning technology. Breathable mesh upper.',
    },
    {
        id: '6',
        name: 'Essential Backpack',
        price: 12750000,
        oldPrice: null,
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=500&fit=crop',
        category: 'Bags',
        colors: ['#000000', '#2F4F4F', '#8B4513'],
        sizes: [],
        rating: 4.8,
        reviews: 167,
        description: 'Premium essential backpack with laptop compartment. Water-resistant material with multiple pockets.',
    },
    {
        id: '7',
        name: 'Boyfriend Tee',
        price: 1350000,
        oldPrice: null,
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=500&fit=crop',
        category: 'Woman',
        colors: ['#FFFFFF', '#000000', '#808080'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        rating: 4.4,
        reviews: 312,
        description: 'Relaxed fit boyfriend tee made from 100% organic cotton. Soft and breathable for everyday wear.',
    },
    {
        id: '8',
        name: 'Jordan 1 Retro High',
        price: 3500000,
        oldPrice: null,
        image: 'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=400&h=500&fit=crop',
        category: 'Shoes',
        colors: ['#000000', '#FF0000', '#FFFFFF'],
        sizes: ['38', '39', '40', '41', '42', '43', '44'],
        rating: 4.9,
        reviews: 567,
        description: 'Iconic Jordan 1 Retro High. Premium leather construction with Air-Sole unit for cushioning.',
    },
    {
        id: '9',
        name: 'Fashion Shop Watch',
        price: 11200000,
        oldPrice: null,
        image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=500&fit=crop',
        category: 'All',
        colors: ['#C0C0C0', '#FFD700', '#000000'],
        sizes: [],
        rating: 4.7,
        reviews: 89,
        description: 'Elegant fashion watch with stainless steel case. Swiss movement with sapphire crystal glass.',
    },
    {
        id: '10',
        name: 'Random Green Olive Recycled',
        price: 1800000,
        oldPrice: null,
        image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&h=500&fit=crop',
        category: 'Man',
        colors: ['#556B2F', '#000000', '#808080'],
        sizes: ['S', 'M', 'L', 'XL'],
        rating: 4.3,
        reviews: 45,
        description: 'Eco-friendly recycled material hoodie in olive green. Comfortable fit with kangaroo pocket.',
    },
    {
        id: '11',
        name: 'Kids Rainbow Sneakers',
        price: 975000,
        oldPrice: null,
        image: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=500&fit=crop',
        category: 'Kids',
        colors: ['#FF69B4', '#87CEEB', '#FFD700'],
        sizes: ['28', '30', '32', '34'],
        rating: 4.8,
        reviews: 76,
        description: 'Colorful rainbow sneakers for kids. Comfortable cushioned sole with easy velcro strap closure.',
    },
    {
        id: '12',
        name: 'Kids Denim Jacket',
        price: 685000,
        oldPrice: null,
        image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=400&h=500&fit=crop',
        category: 'Kids',
        colors: ['#4169E1', '#000000'],
        sizes: ['4Y', '6Y', '8Y', '10Y'],
        rating: 4.6,
        reviews: 38,
        description: 'Stylish denim jacket for kids. Soft cotton lining with classic button closure.',
    },
];

export const banners = [
    {
        id: '1',
        title: 'New Collection',
        subtitle: 'Discover our latest arrivals',
        image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=400&fit=crop',
    },
    {
        id: '2',
        title: 'Summer Sale',
        subtitle: 'Up to 50% off selected items',
        image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&h=400&fit=crop',
    },
    {
        id: '3',
        title: 'Premium Quality',
        subtitle: 'Crafted with care',
        image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&h=400&fit=crop',
    },
];

export const onboardingData = [
    {
        id: '1',
        title: 'Discover Our New\nCollection',
        subtitle: 'Easy shopping for all your needs just in hand, trusted by millions of people in the world.',
        image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=800&fit=crop&crop=faces',
        dark: true,
    },
    {
        id: '2',
        title: 'Order your Style',
        subtitle: 'More than a thousand of our bags are available for your luxury',
        image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=800&fit=crop',
        dark: true,
    },
    {
        id: '3',
        title: '',
        subtitle: '',
        image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=800&fit=crop&crop=faces',
        dark: false,
    },
];

export const topTags = [
    'Fashion', 'Shoes', 'Electronics', 'Furniture', 'Bags',
    'Watches', 'Sports', 'Accessories', 'Home', 'Beauty',
];

export const recentSearches = [
    'Nike Air Max', 'Leather Bag', 'Summer Dress', 'Smart Watch',
];

export const paymentMethods = [
    { id: '1', name: 'Google Pay', icon: 'logo-google' },
    { id: '2', name: 'Mastercard', icon: 'card-outline' },
    { id: '3', name: 'Apple Pay', icon: 'logo-apple' },
    { id: '4', name: 'Cash on delivery', icon: 'cash-outline' },
    { id: '5', name: 'PayPal', icon: 'logo-paypal' },
];

export const accountMenuItems = [
    { id: '1', title: 'My Orders', icon: 'receipt-outline', badge: '3' },
    { id: '2', title: 'Wishlist', icon: 'heart-outline', badge: '12' },
    { id: '3', title: 'Delivery Address', icon: 'location-outline', badge: null },
    { id: '4', title: 'Payment Methods', icon: 'card-outline', badge: null },
    { id: '5', title: 'Notifications', icon: 'notifications-outline', badge: '5' },
    { id: '6', title: 'Language', icon: 'language-outline', badge: null },
    { id: '7', title: 'Help Center', icon: 'help-circle-outline', badge: null },
    { id: '8', title: 'About Us', icon: 'information-circle-outline', badge: null },
];

export const storeLocations = [
    {
        id: '1',
        name: 'SnapShop Grand Indonesia',
        address: 'Jl. M.H. Thamrin No.1, Menteng',
        city: 'Jakarta Pusat',
        hours: '10:00 - 22:00',
        distance: '2.3 km',
        phone: '+62 21 2358 0001',
    },
    {
        id: '2',
        name: 'SnapShop Plaza Senayan',
        address: 'Jl. Asia Afrika No.8, Gelora',
        city: 'Jakarta Selatan',
        hours: '10:00 - 21:00',
        distance: '4.1 km',
        phone: '+62 21 572 5555',
    },
    {
        id: '3',
        name: 'SnapShop Mall Kelapa Gading',
        address: 'Jl. Boulevard Barat Raya, Kelapa Gading',
        city: 'Jakarta Utara',
        hours: '10:00 - 21:30',
        distance: '8.7 km',
        phone: '+62 21 4585 1234',
    },
    {
        id: '4',
        name: 'SnapShop Summarecon Bekasi',
        address: 'Jl. Boulevard Ahmad Yani, Marga Mulya',
        city: 'Bekasi',
        hours: '10:00 - 22:00',
        distance: '15.2 km',
        phone: '+62 21 2957 8888',
    },
    {
        id: '5',
        name: 'SnapShop Living World Alam Sutera',
        address: 'Jl. Alam Sutera Boulevard Kav.21, Pakualam',
        city: 'Tangerang Selatan',
        hours: '10:00 - 22:00',
        distance: '18.5 km',
        phone: '+62 21 2900 5678',
    },
];

export const courierServices = [
    {
        id: '1',
        name: 'JNE Regular',
        courier: 'JNE',
        estimatedDays: '2-3 hari',
        price: 15000,
        icon: 'cube-outline',
    },
    {
        id: '2',
        name: 'J&T Express',
        courier: 'J&T',
        estimatedDays: '1-2 hari',
        price: 18000,
        icon: 'flash-outline',
    },
    {
        id: '3',
        name: 'SiCepat REG',
        courier: 'SiCepat',
        estimatedDays: '1-2 hari',
        price: 17000,
        icon: 'rocket-outline',
    },
    {
        id: '4',
        name: 'GoSend Same Day',
        courier: 'Gojek',
        estimatedDays: 'Hari ini',
        price: 25000,
        icon: 'bicycle-outline',
    },
    {
        id: '5',
        name: 'GrabExpress Instant',
        courier: 'Grab',
        estimatedDays: '1-2 jam',
        price: 35000,
        icon: 'car-outline',
    },
];

export const productReviews = [
    {
        id: '1',
        productId: '1',
        userName: 'Sarah M.',
        userAvatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop',
        rating: 5,
        date: '2 hari lalu',
        text: 'Kualitas tasnya luar biasa! Kulit asli yang sangat lembut dan jahitannya rapi. Sangat puas dengan pembelian ini. Recommended! 🖤',
        photos: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=200&h=200&fit=crop'],
        helpful: 24,
    },
    {
        id: '2',
        productId: '1',
        userName: 'Andi W.',
        userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
        rating: 4,
        date: '1 minggu lalu',
        text: 'Bagus banget, cuma agak berat kalau isi banyak. Tapi build quality-nya premium sekali. Worth the price.',
        photos: [],
        helpful: 12,
    },
    {
        id: '3',
        productId: '1',
        userName: 'Dina R.',
        userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
        rating: 5,
        date: '2 minggu lalu',
        text: 'Packaging-nya premium, sesuai dengan harga. Strap-nya bisa di-adjust dan sangat nyaman. Love it! ❤️',
        photos: [],
        helpful: 8,
    },
    {
        id: '4',
        productId: '2',
        userName: 'Budi S.',
        userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
        rating: 5,
        date: '3 hari lalu',
        text: 'Jacket-nya keren banget, bahannya tebal tapi tidak gerah. Cocok untuk daily wear.',
        photos: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=200&h=200&fit=crop'],
        helpful: 18,
    },
    {
        id: '5',
        productId: '3',
        userName: 'Lisa K.',
        userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop',
        rating: 4,
        date: '5 hari lalu',
        text: 'Sneakers-nya nyaman dan stylish. Sizenya true to size. Pengiriman cepat!',
        photos: [],
        helpful: 6,
    },
    {
        id: '6',
        productId: '4',
        userName: 'Rini P.',
        userAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop',
        rating: 5,
        date: '1 hari lalu',
        text: 'Dress-nya cantik sekali! Bahannya adem dan cutting-nya pas di badan. Warna sesuai foto. 💕',
        photos: [],
        helpful: 15,
    },
];

export const vouchers = [
    {
        id: '1',
        code: 'WELCOME10',
        title: 'Welcome Discount',
        description: 'Diskon 10% untuk pembelian pertama',
        discountType: 'percentage' as const,
        discountValue: 10,
        minPurchase: 500000,
        maxDiscount: 200000,
        validUntil: '31 Mar 2026',
        isUsed: false,
    },
    {
        id: '2',
        code: 'HEMAT50K',
        title: 'Hemat Rp50.000',
        description: 'Potongan langsung Rp50.000',
        discountType: 'fixed' as const,
        discountValue: 50000,
        minPurchase: 300000,
        maxDiscount: 50000,
        validUntil: '15 Mar 2026',
        isUsed: false,
    },
    {
        id: '3',
        code: 'FREESHIP',
        title: 'Free Ongkir',
        description: 'Gratis ongkir untuk semua pengiriman',
        discountType: 'shipping' as const,
        discountValue: 0,
        minPurchase: 200000,
        maxDiscount: 30000,
        validUntil: '28 Feb 2026',
        isUsed: true,
    },
    {
        id: '4',
        code: 'SNAP20',
        title: 'SnapShop Special',
        description: 'Diskon 20% khusus member',
        discountType: 'percentage' as const,
        discountValue: 20,
        minPurchase: 1000000,
        maxDiscount: 500000,
        validUntil: '30 Apr 2026',
        isUsed: false,
    },
    {
        id: '5',
        code: 'PAYDAY100',
        title: 'Payday Sale',
        description: 'Potongan Rp100.000 saat gajian',
        discountType: 'fixed' as const,
        discountValue: 100000,
        minPurchase: 750000,
        maxDiscount: 100000,
        validUntil: '5 Mar 2026',
        isUsed: false,
    },
];
